### PR TITLE
Added swedish translation

### PR DESCRIPTION
**Pull request by robinhellstrom**
Hope this helps, could I get an invite to test the app? ;-)

### CODE REVIEW

**Review by robinhellstrom — COMMENTED** [review]
Hope this helps, could I get an invite to test the app? ;-)

**Comment by Ixam97** [comment]
> Hope this helps, could I get an invite to test the app? ;-)

You can actually delete all files but the `strings.xml` from the `values-sv` folder. Or do you want a swedish specific styling for the app? :P

Contact me with my mail address shown on my profile page regarding test access.

**Comment by robinhellstrom** [comment]
> > Hope this helps, could I get an invite to test the app? ;-)
> 
> You can actually delete all files but the `strings.xml` from the `values-sv` folder. Or do you want a swedish specific styling for the app? :P
> 
> Contact me via my mail address shown on my profile page regarding test access.

I'm no Yoda i XML-markup, my biggest contribution would be that I speak Swedish ;-) I think many user might be from Sweden for this type of app.

I'll send an email to you.

**Comment by Ixam97** [comment]
@robinhellstrom if you check that checkbox "Allow edits from maintainers" on the right I can edit your pull request and delete the unneccessary files before merging 😉

**Comment by robinhellstrom** [comment]
> @robinhellstrom if you check that checkbox "Allow edits from maintainers" on the right I can edit your pull request and delete the unneccessary files before merging wink

Yes, that's active now.

**Comment by jschlyter** [comment]
Good work! Some comments:
- Perhaps we should  "kurva" or "graf" instead of "diagram"?
- Generally, cross check the translations with the german version will most likely result in better wordings as I understand this is the native language of @Ixam97

**Pull request merged**
