### PR TITLE
tweek some Swedish terms

### PR DESCRIPTION
**Pull request by jschlyter**
Update some Swedish terms. Ping @robinhellstrom.

Related to #62

### CODE REVIEW

**Comment by robinhellstrom** [comment]
"Kurva" is not at correct swedish word for "trendlinje". Our east-european friends will also find the word "kurva" a little embarrassing to use ;-)

**Comment by robinhellstrom** [comment]
"Kurva" is not at correct swedish word for "trendlinje". Our east-european friends will also find the word "kurva" a little embarrassing to use ;-)

**Comment by robinhellstrom** [comment]
> Update some Swedish terms. Ping @robinhellstrom.
> 
> Related to #62 

"Kurva" is not at correct swedish word for "trendlinje". Our east-european friends will also find the word "kurva" a little embarrassing to use ;-)

**Comment by jschlyter** [comment]
@robinhellstrom The german term "Geschwindigkeitsverlauf" is "Hastighetskurva" in Swedish, it can never be a "diagram". What "kurva" means in other languages is not really important, is it? :-)  They will have plenty of issues with all other car settings in that case (e.g., "kurvljus").

(marking PR as draft until the Swedish agree)

**Comment by robinhellstrom** [comment]
> @robinhellstrom The german term "Geschwindigkeitsverlauf" is "Hastighetskurva" in Swedish, it can never be a "diagram". What "kurva" means in other languages is not really important, is it? :-)  They will have plenty of issues with all other car settings in that case (e.g., "kurvljus").
> 
> (marking PR as draft until the Swedes agree)

Okey, let it be "kurva" until anyone else from Sweden disagrees ;-)

**Comment by jschlyter** [comment]
Adding some more tweeks. Translation from German to Swedish (without English) yields better results IMHO.

**Pull request merged**
